//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generateur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public int IdDate { get; set; }
        public System.DateTime datedebut { get; set; }
        public int duree { get; set; }
        public int Customer { get; set; }
        public int Cat { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Customer Customer1 { get; set; }
    }
}
